from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app import __version__
from app.api.v1 import api_router
from app.core.config import settings
from app.core.database import engine
from app.core.logging import RequestLogMiddleware, configure_logging
from app.core.ratelimit import RateLimitMiddleware
from app.core.sentry import init_sentry

# Init Sentry BEFORE configuring logging so its breadcrumbs pick up
# every log record. No-op when SENTRY_DSN is empty.
init_sentry()
configure_logging()


@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    yield
    await engine.dispose()


app = FastAPI(
    title=settings.APP_NAME,
    version=__version__,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
    lifespan=lifespan,
)

# Middleware ordering matters. Starlette runs the LAST-added middleware
# OUTERMOST, so CORS is added last on purpose: it must wrap the rate
# limiter and the request logger. Otherwise a response generated by an
# inner middleware (e.g. the rate limiter's 429 JSONResponse) — or a
# preflight OPTIONS short-circuited before it reaches CORS — comes back
# WITHOUT an Access-Control-Allow-Origin header and the browser blocks it
# ("No 'Access-Control-Allow-Origin' header"). With CORS outermost, every
# response (success, 401, 429, error) carries CORS headers and preflight
# requests are answered before any inner middleware runs.
if settings.RATE_LIMIT_ENABLED:
    app.add_middleware(RateLimitMiddleware)

app.add_middleware(RequestLogMiddleware)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    # `allow_origin_regex` is OR-ed with the explicit list; in dev it lets
    # any localhost / 127.0.0.1 port (Vite 5173, the :3000 dev server, …)
    # through without editing CORS_ORIGINS. Production sets explicit
    # origins and can clear the regex via the env var.
    allow_origin_regex=settings.CORS_ORIGIN_REGEX or None,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router, prefix=settings.API_V1_PREFIX)


@app.get("/", include_in_schema=False)
async def root() -> dict[str, str]:
    return {
        "name": settings.APP_NAME,
        "version": __version__,
        "docs": "/docs",
        "api": settings.API_V1_PREFIX,
    }
